'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Check, Clock3, MapPin, Sparkles } from 'lucide-react';
import { demoUser, sessions } from '@/lib/demo-data';
export default function Schedule(){
 const [day,setDay]=useState('2026-05-29'); const [saved,setSaved]=useState<string[]>(()=>{if(typeof window==='undefined')return [];try{return JSON.parse(localStorage.getItem('eventos-schedule')||'[]')}catch{return []}});
 const list=useMemo(()=>sessions.filter(s=>s.date===day),[day]);
 const toggle=(id:string)=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem('eventos-schedule',JSON.stringify(next));};
 return <Shell title="My schedule"><div className="mb-6 flex gap-2"><button onClick={()=>setDay('2026-05-29')} className={`rounded-2xl px-4 py-3 font-bold ${day==='2026-05-29'?'bg-slate-950 text-white':'bg-white border'}`}>Day 1 · May 29</button><button onClick={()=>setDay('2026-05-30')} className={`rounded-2xl px-4 py-3 font-bold ${day==='2026-05-30'?'bg-slate-950 text-white':'bg-white border'}`}>Day 2 · May 30</button></div><div className="mb-6 rounded-3xl border border-indigo-100 bg-indigo-50 p-5"><div className="flex gap-3"><Sparkles className="mt-1 text-indigo-600"/><div><b>Personalized for {demoUser.name}</b><p className="mt-1 text-sm text-slate-600">Your recommendations prioritize AI agents, LLMs, deployment and startup networking.</p></div></div></div><div className="space-y-3">{list.map(s=><div key={s.id} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center"><div className="w-28 shrink-0 text-sm font-black"><Clock3 className="mr-1 inline" size={15}/>{s.startTime}<div className="mt-1 text-xs font-medium text-slate-400">{s.endTime}</div></div><div className="flex-1"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{s.track}</span><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-bold text-indigo-700">{s.sessionType}</span></div><h3 className="mt-2 text-lg font-black">{s.title}</h3><p className="mt-1 text-sm text-slate-500">{s.speaker} · {s.speakerRole}</p><p className="mt-2 text-xs font-bold text-slate-400"><MapPin className="mr-1 inline" size={13}/>{s.venue}</p></div><button onClick={()=>toggle(s.id)} className={`rounded-2xl px-4 py-3 text-sm font-bold ${saved.includes(s.id)?'bg-emerald-50 text-emerald-700':'bg-slate-950 text-white'}`}>{saved.includes(s.id)?<><Check className="mr-1 inline" size={16}/>Saved</>:'Add to schedule'}</button></div></div>)}</div></Shell>
}
function Shell({title,children}:{title:string,children:React.ReactNode}){return <main className="min-h-screen bg-[#f6f7fb] text-slate-950"><nav className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center gap-4 px-6 py-4"><Link href="/dashboard"><ArrowLeft size={18}/></Link><span className="font-black">Event<span className="text-indigo-600">OS</span></span><span className="text-slate-300">/</span><h1 className="font-bold">{title}</h1></div></nav><div className="mx-auto max-w-6xl px-6 py-8">{children}</div></main>}
