'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, Bot, CalendarDays, Clock3, MapPin, Sparkles, Utensils, Users, Zap } from 'lucide-react';
import { demoUser, recommendedSessions, type DemoSession } from '@/lib/demo-data';

function Card({children,className='' }:{children:React.ReactNode,className?:string}){return <div className={`rounded-3xl border border-slate-200 bg-white shadow-sm ${className}`}>{children}</div>}
export default function Dashboard(){
 const [saved]=useState<string[]>(()=>{if(typeof window==='undefined')return [];try{return JSON.parse(localStorage.getItem('eventos-schedule')||'[]')}catch{return []}});
 const recs=recommendedSessions();
 return <main className="min-h-screen bg-[#f6f7fb] text-slate-950"><nav className="border-b bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link href="/" className="text-xl font-black tracking-tight">Event<span className="text-indigo-600">OS</span></Link><div className="flex items-center gap-2 text-sm"><span className="hidden text-slate-500 sm:inline">Mumbai Tech Week 2026</span><Link href="/profile" className="rounded-full bg-slate-100 px-4 py-2 font-semibold">{demoUser.name}</Link></div></div></nav>
 <div className="mx-auto max-w-7xl px-6 py-8"><div className="mb-8 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="mb-2 text-sm font-bold uppercase tracking-[.18em] text-indigo-600">AI in Action · May 29–30</p><h1 className="text-4xl font-black tracking-tight sm:text-5xl">Good morning, {demoUser.name.split(' ')[0]}.</h1><p className="mt-3 max-w-2xl text-lg text-slate-500">Your event companion is ready. Here’s what EventOS thinks you should do next.</p></div><Link href="/copilot" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 py-3 font-bold text-white shadow-lg hover:bg-indigo-700"><Bot size={18}/> Ask EventOS</Link></div>
 <div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><Card className="overflow-hidden"><div className="bg-slate-950 p-6 text-white"><div className="flex items-center gap-2 text-indigo-300"><Sparkles size={18}/><span className="text-sm font-bold">NEXT UP · AI RECOMMENDATION</span></div><h2 className="mt-4 text-2xl font-black">{recs[0].title}</h2><p className="mt-2 max-w-xl text-slate-300">{recs[0].description}</p><div className="mt-5 flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-white/10 px-3 py-1.5"><Clock3 className="mr-1 inline" size={14}/>{recs[0].startTime}–{recs[0].endTime}</span><span className="rounded-full bg-white/10 px-3 py-1.5"><MapPin className="mr-1 inline" size={14}/>{recs[0].venue}</span></div></div><div className="grid grid-cols-3 divide-x border-t"><div className="p-5"><div className="text-2xl font-black">{saved.length}</div><div className="text-xs font-semibold text-slate-500">SAVED SESSIONS</div></div><div className="p-5"><div className="text-2xl font-black">AI</div><div className="text-xs font-semibold text-slate-500">YOUR TOP TRACK</div></div><div className="p-5"><div className="text-2xl font-black">13</div><div className="text-xs font-semibold text-slate-500">VENUE ZONES</div></div></div></Card>
 <Card className="p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-slate-400">YOUR EVENTOS</p><h3 className="mt-1 text-xl font-black">At a glance</h3></div><Zap className="text-indigo-600"/></div><div className="mt-6 space-y-4"><Quick icon={<CalendarDays/>} label="My schedule" href="/schedule"/><Quick icon={<MapPin/>} label="Explore venue" href="/map"/><Quick icon={<Utensils/>} label="Plan lunch" href="/food"/><Quick icon={<Users/>} label="Meet the right people" href="/network"/><Quick icon={<Zap/>} label="Safety & assistance" href="/alerts"/><Quick icon={<Bot/>} label="Organizer demo" href="/organizer/command"/></div></Card></div>
 <section className="mt-8"><div className="mb-4 flex items-end justify-between"><div><p className="text-sm font-bold text-indigo-600">WHY THESE?</p><h2 className="text-2xl font-black">Recommended for you</h2></div><Link href="/schedule" className="text-sm font-bold text-slate-600">See schedule <ArrowRight className="inline" size={15}/></Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{recs.map((s,i)=><SessionCard key={s.id} session={s} rank={i+1}/>)}</div></section>
 <section className="mt-8 rounded-3xl border border-indigo-100 bg-indigo-50 p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-indigo-700">EventOS Copilot</p><h2 className="mt-1 text-2xl font-black">Ask a normal question. Get an event-aware answer.</h2><p className="mt-2 text-slate-600">Try “What should I attend next?” or “Find me an AI startup to meet.”</p></div><Link href="/copilot" className="shrink-0 rounded-2xl bg-indigo-600 px-5 py-3 text-center font-bold text-white hover:bg-indigo-700">Open Copilot</Link></div></section>
 <p className="mt-8 text-center text-xs text-slate-400">EventOS uses official Mumbai Tech Week public event information. Operational intelligence shown in the prototype is simulated.</p></div></main>
}
function Quick({icon,label,href}:{icon:React.ReactNode,label:string,href:string}){return <Link href={href} className="flex items-center gap-4 rounded-2xl border p-4 transition hover:border-indigo-200 hover:bg-indigo-50"><span className="rounded-xl bg-indigo-50 p-2 text-indigo-600">{icon}</span><span className="font-bold">{label}</span><ArrowRight className="ml-auto text-slate-400" size={17}/></Link>}
function SessionCard({session,rank}:{session:DemoSession,rank:number}){return <Card className="p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-bold text-indigo-700">#{rank} MATCH</span><span className="text-xs font-bold text-slate-400">{session.track}</span></div><h3 className="mt-4 font-black leading-tight">{session.title}</h3><p className="mt-2 text-sm text-slate-500">{session.company} · {session.speaker}</p><div className="mt-4 text-xs font-semibold text-slate-500">{session.startTime} · {session.venue}</div></Card>}
